version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis_chat
    volumes:
      - ./redisdata:/bitnami/redis/data
    ports:
      - 6379:6379
    environment:
      - REDIS_AOF_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - chat

  mongodb:
    hostname: mongo_chat
    container_name: mongo_chat
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - '127.0.0.1:27017:27017'
    networks:
      - chat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:13-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db
        POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

networks:
  chat:
    driver: bridge

volumes:
  mongodata:
  db-data:

